server:
  port: 9050
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kanban
  application:
    name: task-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true